version: '3.9'

services:

  redis:
    image: redis:7.4-alpine
    container_name: supplychain_redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - supplychain

  rabbitmq:
    image: rabbitmq:4-management
    container_name: supplychain_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - supplychain

volumes:
  redis_data:
  rabbitmq_data:

networks:
  supplychain:
    driver: bridge
