import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

/**
 * SafeHtmlPipe
 * ------------
 * Marks a string as trusted HTML so Angular's template engine
 * will render it without stripping tags.
 *
 * Used by the AI assistant to render newlines inside message bubbles
 * as <br> tags (the template uses `white-space: pre-wrap` so plain
 * strings already work; this pipe is a safety net for future markdown).
 *
 * Usage: {{ msg.text | safeHtml }}
 */
@Pipe({
  name: 'safeHtml',
  standalone: false,
})
export class SafeHtmlPipe implements PipeTransform {
  constructor(private sanitizer: DomSanitizer) {}

  transform(value: string): SafeHtml {
    // We trust content generated by our own backend.
    return this.sanitizer.bypassSecurityTrustHtml(value);
  }
}
