import { environment } from '../../../environments/environment';

function getBaseUrl(serviceUrl: string): string {
  return environment.useDirect ? serviceUrl : environment.gatewayUrl;
}

export const API_ENDPOINTS = {
  auth: {
    login: () => `${getBaseUrl(environment.identityServiceUrl)}/api/auth/login`,
    loginVerifyOtp: () => `${getBaseUrl(environment.identityServiceUrl)}/api/auth/login/verify-otp`,
    refresh: () => `${getBaseUrl(environment.identityServiceUrl)}/api/auth/refresh`,
    logout: () => `${getBaseUrl(environment.identityServiceUrl)}/api/auth/logout`,
    logoutAll: () => `${getBaseUrl(environment.identityServiceUrl)}/api/auth/logout-all`,
    register: () => `${getBaseUrl(environment.identityServiceUrl)}/api/auth/register`,
    registerVerifyOtp: () => `${getBaseUrl(environment.identityServiceUrl)}/api/auth/register/verify-otp`,
    forgotPassword: () => `${getBaseUrl(environment.identityServiceUrl)}/api/auth/forgot-password`,
    forgotPasswordReset: () => `${getBaseUrl(environment.identityServiceUrl)}/api/auth/forgot-password/reset`,
  },
  users: {
    profilePicture: () => `${getBaseUrl(environment.identityServiceUrl)}/api/users/profile-picture`,
    changePassword: () => `${getBaseUrl(environment.identityServiceUrl)}/api/users/change-password`,
  },
  shippingAddress: {
    base: () => `${getBaseUrl(environment.identityServiceUrl)}/api/shipping-addresses`,
    byId: (id: string) => `${getBaseUrl(environment.identityServiceUrl)}/api/shipping-addresses/${id}`,
    setDefault: (id: string) => `${getBaseUrl(environment.identityServiceUrl)}/api/shipping-addresses/${id}/set-default`,
  },
  catalog: {
    products: () => `${getBaseUrl(environment.catalogServiceUrl)}/api/products`,
    productById: (id: string) => `${getBaseUrl(environment.catalogServiceUrl)}/api/products/${id}`,
    hardDeleteProduct: (id: string) => `${getBaseUrl(environment.catalogServiceUrl)}/api/products/${id}/hard-delete`,
    activateProduct: (id: string) => `${getBaseUrl(environment.catalogServiceUrl)}/api/products/${id}/activate`,
    categories: () => `${getBaseUrl(environment.catalogServiceUrl)}/api/categories`,
    categoryById: (id: string) => `${getBaseUrl(environment.catalogServiceUrl)}/api/categories/${id}`,
    activateCategory: (id: string) => `${getBaseUrl(environment.catalogServiceUrl)}/api/categories/${id}/activate`,
    deactivateCategory: (id: string) => `${getBaseUrl(environment.catalogServiceUrl)}/api/categories/${id}/deactivate`,
    toggleFavorite: (id: string) => `${getBaseUrl(environment.catalogServiceUrl)}/api/products/${id}/favorite`,
    favorites: () => `${getBaseUrl(environment.catalogServiceUrl)}/api/products/favorites`,
  },
  orders: {
    base: () => `${getBaseUrl(environment.orderServiceUrl)}/api/orders`,
    uploadReturnImage: () => `${getBaseUrl(environment.orderServiceUrl)}/api/orders/upload-return-image`,
    myOrders: () => `${getBaseUrl(environment.orderServiceUrl)}/api/orders/my`,
    orderById: (id: string) => `${getBaseUrl(environment.orderServiceUrl)}/api/orders/${id}`,
    approveOrder: (id: string) => `${getBaseUrl(environment.orderServiceUrl)}/api/orders/${id}/approve`,
    cancelOrder: (id: string) => `${getBaseUrl(environment.orderServiceUrl)}/api/orders/${id}/cancel`,
    readyForDispatch: (id: string) => `${getBaseUrl(environment.orderServiceUrl)}/api/orders/${id}/ready-for-dispatch`,
    markInTransit: (id: string) => `${getBaseUrl(environment.orderServiceUrl)}/api/orders/${id}/in-transit`,
    markDelivered: (id: string) => `${getBaseUrl(environment.orderServiceUrl)}/api/orders/${id}/delivered`,
  },
  returns: {
    raiseReturn: (orderId: string) => `${getBaseUrl(environment.orderServiceUrl)}/api/orders/${orderId}/returns`,
    myReturns: () => `${getBaseUrl(environment.orderServiceUrl)}/api/returns/my`,
    allReturns: () => `${getBaseUrl(environment.orderServiceUrl)}/api/returns`,
    approve: (id: string) => `${getBaseUrl(environment.orderServiceUrl)}/api/returns/${id}/approve`,
    reject: (id: string) => `${getBaseUrl(environment.orderServiceUrl)}/api/returns/${id}/reject`,
  },
  logistics: {
    tracking: (orderId: string) => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/tracking/${orderId}`,
    shipments: () => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/shipments`,
    pendingShipments: () => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/shipments/pending`,
    assignAgent: () => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/shipments/assign-agent`,
    updateShipmentStatus: (orderId: string) => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/shipments/${orderId}/status`,
    agents: () => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/agents`,
    availableAgents: () => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/agents/available`,
    rateShipment: (shipmentId: string) => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/shipments/${shipmentId}/rate`,
    vehicles: () => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/vehicles`,
    myShipments: () => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/shipments/mine`,
    allAgents: () => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/agents`,
    agentMe: () => `${getBaseUrl(environment.logisticsServiceUrl)}/api/logistics/agents/me`,
  },
  payment: {
    invoices: () => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/invoices`,
    myInvoices: () => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/invoices/my`,
    invoiceByOrderId: (orderId: string) => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/invoices/order/${orderId}`,
    invoicesByDealer: (dealerId: string) => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/invoices/dealer/${dealerId}`,
    invoiceById: (id: string) => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/invoices/${id}`,
    downloadInvoice: (id: string) => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/invoices/${id}/download`,
    generateInvoice: () => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/invoices/generate`,
    creditCheck: (dealerId: string) => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/dealers/${dealerId}/credit-check`,
    creditAccount: (dealerId: string) => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/dealers/${dealerId}/credit-account`,
    creditLimit: (dealerId: string) => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/dealers/${dealerId}/credit-limit`,
    razorpayCreateOrder: () => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/razorpay/create-order`,
    razorpayConfirm: () => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/razorpay/confirm`,
    razorpaySimulateCapture: () => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/razorpay/simulate-capture`,
    salesExport: () => `${getBaseUrl(environment.paymentServiceUrl)}/api/payment/admin/sales/export`,
  },
  admin: {
    dealers: () => `${getBaseUrl(environment.identityServiceUrl)}/api/admin/dealers`,
    approveDealer: (id: string) => `${getBaseUrl(environment.identityServiceUrl)}/api/admin/dealers/${id}/approve`,
    rejectDealer: (id: string) => `${getBaseUrl(environment.identityServiceUrl)}/api/admin/dealers/${id}/reject`,
    suspendDealer: (id: string) => `${getBaseUrl(environment.identityServiceUrl)}/api/admin/dealers/${id}/suspend`,
    reactivateDealer: (id: string) => `${getBaseUrl(environment.identityServiceUrl)}/api/admin/dealers/${id}/reactivate`,
    deleteDealer: (id: string) => `${getBaseUrl(environment.identityServiceUrl)}/api/admin/dealers/${id}`,
  },
  superAdmin: {
    createAdmin: () => `${getBaseUrl(environment.identityServiceUrl)}/api/super-admin/create-admin`,
    viewAdmins: () => `${getBaseUrl(environment.identityServiceUrl)}/api/super-admin/view-admins`,
  },
  notification: {
    inbox: () => `${getBaseUrl(environment.notificationServiceUrl)}/api/notifications/inbox`,
    inboxUnreadCount: () => `${getBaseUrl(environment.notificationServiceUrl)}/api/notifications/inbox/unread-count`,
    inboxMarkRead: (id: string) => `${getBaseUrl(environment.notificationServiceUrl)}/api/notifications/inbox/${id}/read`,
    inboxMarkAllRead: () => `${getBaseUrl(environment.notificationServiceUrl)}/api/notifications/inbox/read-all`,
    templates: () => `${getBaseUrl(environment.notificationServiceUrl)}/api/notifications/templates`,
    templateById: (id: string) => `${getBaseUrl(environment.notificationServiceUrl)}/api/notifications/templates/${id}`,
  },
  inventory: {
    base: () => `${getBaseUrl(environment.catalogServiceUrl)}/api/inventory`,
    restock: () => `${getBaseUrl(environment.catalogServiceUrl)}/api/inventory/restock`,
    snapshot: () => `${getBaseUrl(environment.catalogServiceUrl)}/api/inventory/snapshot`,
  },
};
